name: Maven CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Package with Maven
        run: mvn clean package

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=giriraj7singh-code_jenkins-maven-demo
          -Dsonar.organization=giriraj7singh-code
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=$SONAR_TOKEN

      - name: Build Docker Image
        run: docker build -t jenkins-maven-demo:${{ github.run_number }} .

      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'jenkins-maven-demo:${{ github.run_number }}'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: docker tag jenkins-maven-demo:${{ github.run_number }} girirajs7/jenkins-maven-demo:${{ github.run_number }}

      - name: Push Docker Image
        run: docker push girirajs7/jenkins-maven-demo:${{ github.run_number }}
